Added Doug Finke's ImportExcel module
ClaudioESSilva/PowerShellModulesCentral pull request #11
Opened 2017-10-04 13:36 UTC by dfinke

Let me know of changes needed. Thanks for putting this together

2017-10-05 09:27 UTC, ClaudioESSilva requested changes
Thanks Doug. Few request changes.

2017-10-05 09:27 UTC, ClaudioESSilva commented on Modules/ImportExcel.md
> +| PowerShell 4.0 | [Doug Finke](https://twitter.com/dfinke) | [Github](https://github.com/dfinke/ImportExcel) | May 2015 | powershell, excel |
Please add your blog URL on the same cell of Twitter.

2017-10-05 09:27 UTC, ClaudioESSilva commented on Modules/ImportExcel.md
> +* On the PowerShell Gallery - [ImportExcel](https://www.powershellgallery.com/packages/ImportExcel)
Please, add a new cell on the table with title PowerShell gallery and the URL on the value.
I will go through others modules add this too so it becomes coherent.
It's a good addition. Thanks.

2017-10-05 09:27 UTC, ClaudioESSilva commented on Modules/ImportExcel.md
> +* [Introducing the PowerShell Excel Module](https://blogs.technet.microsoft.com/heyscriptingguy/2015/11/25/introducing-the-powershell-excel-module-2/)
Add your name and the (b | t) before the list of posts. You can check this on any other module md file.

2017-10-05 09:27 UTC, ClaudioESSilva commented on Modules/ImportExcel.md
> +
Same as before. Add your name and (b | t)

Also order the subtitles alphabetically. Switch tracking ups with the last one.

Curiosity: why the last has the [image] and the others is empty?

2017-10-05 09:27 UTC, ClaudioESSilva commented on readme.md
> +  * [ImportExcel](https://github.com/ClaudioESSilva/PowerShellModulesCentral/blob/master/Modules/ImportExcel.md)
You can discard the changes om readme.md file from the PR. I will update it when merged

2017-10-05 09:28 UTC, ClaudioESSilva commented
Thanks for your contribution @dfinke ! Asked for some minor changes. Let me know if you have any question

2017-10-05 21:19 UTC, ClaudioESSilva commented
@dfinke If you prefer I can do those minor adjustments. Let me know. Thanks

2017-10-06 00:06 UTC, dfinke commented
Please do. Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Cláudio Silva <notifications@github.com>
Sent: Thursday, October 5, 2017 5:19:28 PM
To: ClaudioESSilva/PowerShellModulesCentral
Cc: Doug Finke; Mention
Subject: Re: [ClaudioESSilva/PowerShellModulesCentral] Added Doug Finke's ImportExcel module (#11)


@dfinke<https://github.com/dfinke> If you prefer I can do those minor adjustments. Let me know. Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ClaudioESSilva/PowerShellModulesCentral/pull/11#issuecomment-334595292>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAEGuv8KR-ftY08lJQDT01ixdipnUq26ks5spUfggaJpZM4Ptn8g>.

2017-10-06 07:51 UTC, merged

2017-10-06 07:51 UTC, ClaudioESSilva commented
Thanks for your contribution @dfinke !