Added AutomatedLab
ClaudioESSilva/PowerShellModulesCentral pull request #15
Opened 2017-11-23 15:23 UTC by nyanhp

No video links yet, there will hopefully be an update...
Thanks for the great work @ClaudioESSilva !

2017-11-27 17:43 UTC, ClaudioESSilva requested changes
Thanks for submitting the PR!
Please see my comments.

2017-11-27 17:43 UTC, ClaudioESSilva commented on readme.md
> +  * [AutomatedLab](https://github.com/ClaudioESSilva/PowerShellModulesCentral/blob/master/Modules/AutomatedLab.md)
Please remove this file from the PR. I will add it later.

2017-11-27 17:43 UTC, ClaudioESSilva commented on Modules/AutomatedLab.md
> +| PS v5.0+ | Raimund Andrée (<a href="https://twitter.com/raimundandree" target="_blank">t</a>), Per Pedersen, Jan-Hendrik Peters (<a href="https://twitter.com/nyanhp">) | [Github](https://github.com
Please fix the Jan-Hendrik Peters twitter URL
Use "N/A" instead of "nA"
Add the month of creation's date (if you know it )

2017-11-27 21:24 UTC, nyanhp commented
Hi @ClaudioESSilva , pushed the changes to my fork. Thanks for the info!

2017-11-28 10:17 UTC, ClaudioESSilva approved these changes
Thanks!

2017-11-28 10:17 UTC, merged

2017-11-28 10:18 UTC, ClaudioESSilva commented
Thanks for contribtuting @nyanhp ! 
Looking forward for more blog posts and the videos 👍