Add Chronometer by @KevinMarquette
ClaudioESSilva/PowerShellModulesCentral pull request #9
Opened 2017-09-24 21:59 UTC by KevinMarquette

2017-09-24 22:54 UTC, ClaudioESSilva commented on Modules/Chronometer.md
> +| PS v5.0+ | Kevin Marquette (<a href="https://kevinmarquette.github.io/blog/?utm_source=PowerShellModulesCentral&utm_medium=markdown" target="_blank">b</a> \| <a href="https://twitter.com/kevinmarqu
If you don't mind, please write the complete month name and not only the abbreviation.

2017-09-24 22:55 UTC, ClaudioESSilva requested changes
small change

2017-09-24 22:56 UTC, ClaudioESSilva commented
Thanks @KevinMarquette!

Just a small change request.
Will do on the other one you submit and to the other modules that are using abbreviations. to maintain consistency

2017-09-24 23:28 UTC, KevinMarquette commented
I made that correction

2017-09-25 09:27 UTC, ClaudioESSilva approved these changes
Good to go!

2017-09-25 09:28 UTC, merged

2017-09-25 09:28 UTC, ClaudioESSilva commented
Merged.
Thanks again @KevinMarquette !